language: go

install:
  - go get -d -v ./... && go build -v ./...
  - go get -v github.com/stretchr/testify/assert
  - go test -i

go:
  - 1.0
  - 1.1

notifications:
  email:
    - travis@dynport.de
